# Generated by Django 4.1.4 on 2022-12-28 11:16

from django.apps.registry import Apps
from django.core.management.sql import emit_post_migrate_signal
from django.db import migrations
from django.db.backends.base.schema import BaseDatabaseSchemaEditor

from shelter.settings import (READ_CREATE_UPDATE_DELETE_GROUP_NAME,
                              READ_CREATE_UPDATE_GROUP_NAME, READ_GROUP_NAME)


def create_groups(apps: Apps, schema_editor: BaseDatabaseSchemaEditor) -> None:
    emit_post_migrate_signal(2, False, "default")

    group = apps.get_model("auth", "Group")
    permission = apps.get_model("auth", "Permission")

    view_pet, _ = permission.objects.get_or_create(name="Can view Животное")
    change_pet, _ = permission.objects.get_or_create(name="Can change Животное")
    add_pet, _ = permission.objects.get_or_create(name="Can add Животное")
    delete_pet, _ = permission.objects.get_or_create(name="Can delete Животное")

    guest, _ = group.objects.get_or_create(name=READ_GROUP_NAME)
    guest.permissions.add(view_pet)
    user, _ = group.objects.get_or_create(
        name=READ_CREATE_UPDATE_GROUP_NAME,
    )
    user.permissions.add(view_pet, change_pet, add_pet)
    admin, _ = group.objects.get_or_create(
        name=READ_CREATE_UPDATE_DELETE_GROUP_NAME,
    )
    admin.permissions.add(view_pet, change_pet, add_pet, delete_pet)


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "__latest__"),
        ("auth", "__latest__"),
        ("shelter_app", "0001_initial"),
    ]

    operations = [migrations.RunPython(create_groups)]
