# Generated by Django 4.1.4 on 2022-12-28 11:16

from django.db import migrations


def create_groups(apps, schema_editor):
    # TODO используй корректный синтаксис, слова с заглавной буквы только для декларирования классов
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')

    view_pet, _ = Permission.objects.get_or_create(name='Can view Животное')
    change_pet, _ = Permission.objects.get_or_create(name='Can change Животное')
    add_pet, _ = Permission.objects.get_or_create(name='Can change Животное')
    delete_pet, _ = Permission.objects.get_or_create(name='Can delete Животное')

    guest, _ = Group.objects.get_or_create(
        name='guest'
    )
    guest.permissions.add(view_pet)
    user, _ = Group.objects.get_or_create(
        name='user',
    )
    user.permissions.add(view_pet, change_pet, add_pet)
    admin, _ = Group.objects.get_or_create(
        name='admin',
    )
    admin.permissions.add(view_pet, change_pet, add_pet, delete_pet)


class Migration(migrations.Migration):

    dependencies = [
        ("shelter_app", "0002_shelteruser"),
    ]

    operations = [
        migrations.RunPython(create_groups)
    ]
